version: '3.6'

services:
  postgres:
    image: "postgres:11-alpine"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=emailservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DATA=/data
    volumes:
      - db-data:/data

volumes:
  db-data: